export const ARTICLE_HAS_ERRORED = "ARTICLE_HAS_ERRORED";
export const ARTICLE_IS_LOADING = "ARTICLE_IS_LOADING";
export const ARTICLE_FETCH_DATA_SUCCESS = "ARTICLE_FETCH_DATA_SUCCESS";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DEL_ARTICLE = "DEL_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";