export const ADD_ARTICLE = "ADD_ARTICLE";
export const DEL_ARTICLE = "DEL_ARTICLE";
export const CHANGE_ARTICLE = "CHANGE_ARTICLE";
export const CHANGE_ARTICLE = "ARTICLE_HAS_ERRORED";
export const CHANGE_ARTICLE = "ARTICLE_IS_LOADING";
export const CHANGE_ARTICLE = "ARTICLE_FETCH_DATA_SUCCESS";